version: '3.9'
services:
  data:
    build:
      context: .
      dockerfile: src/Services/Data/Data.Api/Dockerfile
    container_name: data
    ports:
      - "5001:8080"
    volumes:
      - data:/data
  inventory:
    build:
      context: .
      dockerfile: src/Services/Inventory/Inventory.Api/Dockerfile
    container_name: inventory
    ports:
      - "5002:8080"
  pricing:
    build:
      context: .
      dockerfile: src/Services/Pricing/Pricing.Api/Dockerfile
    container_name: pricing
    ports:
      - "5003:8080"
  logger:
    build:
      context: .
      dockerfile: src/Services/Logger/Logger.Api/Dockerfile
    container_name: logger
    ports:
      - "5004:8080"
    volumes:
      - logs:/logs
  dispatcher:
    build:
      context: .
      dockerfile: src/Services/Dispatcher/Dispatcher.Api/Dockerfile
    container_name: dispatcher
    depends_on:
      - data
      - inventory
      - pricing
      - logger
    environment:
      PRICING_URL: http://pricing:8080
      INVENTORY_URL: http://inventory:8080
      DATA_URL: http://data:8080
      LOG_URL: http://logger:8080
    ports:
      - "5000:8080"
volumes:
  data:
  logs:
